/* Copyright (c) 2020 Kanari Digital, Inc. */

package com.KanariDigital.app.util


/** log tags
  */
object LogTag {

  // default
  val DEFAULT = "DEFAULT"

  // Zeppelin
  val ZEPPELIN = "ZEPPELIN"

  // app
  val APPLICATION_ID_NONE = "APPLICATION_ID_NONE"
  val PIPELINE_ID_NONE = "PIPELINE_ID_NONE"
  val START_APP = "STARTED_APP"
  val STOP_APP = "STOPPED_APP"
  val BATCH_DURATION = "BATCH_DURATION"

  // error
  val APP_ERROR = "APP_ERROR"
  val APP_ERROR_EVENTHUB_WRITE_FAILED = "APP_ERROR_EVENTHUB_WRITE_FAILED"

  // fatal
  val FATAL_APP_EXIT_ERROR = "FATAL_APP_EXIT_ERROR"
  val FATAL_APPCONFIG_PARSE_ERROR = "FATAL_APPCONFIG_PARSE_ERROR"
  val FATAL_PIPELINECONFIG_PARSE_ERROR = "FATAL_PIPELINECONFIG_PARSE_ERROR"
  val FATAL_PIPELINECONFIG_CONVERT_ERROR = "FATAL_PIPELINECONFIG_CONVERT_ERROR"
  val FATAL_CONFIGPATH_UNDEFINED_ERROR = "FATAL_CONFIGPATH_UNDEFINED_ERROR"


  // counts
  val TRANSFORMED_IDOC_COUNT = "TRANSFORMED_IDOC_COUNT"
  val TRANSFORMED_TOPIC_IDOC = "TRANSFORMED_TOPIC_IDOC"
  val SOURCE_TOPIC_PARTITION_COUNT = "SOURCE_TOPIC_PARTITION_COUNT"
  val SOURCE_TOPIC_COUNT = "SOURCE_TOPIC_COUNT"
  val HBASE_PUT_TABLE_COUNT = "HBASE_PUT_TABLE_COUNT"
  val EVENTHUB_PUT_TABLE_COUNT = "EVENTHUB_PUT_TABLE_COUNT"


  // messages
  val SOURCE_EMPTY = "SOURCE_EMPTY"
  val STORE_OFFSETS = "STORE_OFFSETS"

  val PROCESS_RDD = "PROCESS_RDD"

  val PROCESS_RDD_WRITE_RESULT = "PROCESS_RDD_WRITE_RESULT"
  val PROCESS_RDD_TRANSFORM_WRITE = "PROCESS_RDD_TRANSFORM_WRITE"
  val PROCESS_RDD_HBROWS_WRITE = "PROCESS_RDD_HBROWS_WRITE"

  val PROCESS_RDD_WRITE_HBASE = "PROCESS_WRITE_HBASE"
  val PROCESS_RDD_WRITE_EVENTHUB = "PROCESS_WRITE_EVENTHUB"
  val PROCESS_RDD_WRITE_IDOC = "PROCESS_WRITE_IDOC"

  val TRANSFORM_DATA_FAILED = "TRANSFORM_DATA_FAILED"

}
